# hrApplication Application - Shared Configuration
spring.profiles.active=postgres

# Application Configuration
spring.application.name=HR Application

# Shared JPA Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging Configuration
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Management endpoints (from actuator)
management.endpoints.web.exposure.include=health,info,env

# OAuth2 Resource Server Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/hr-realm