# PostgreSQL Database Profile Configuration
spring.config.activate.on-profile=postgres

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://hrapp-postgres:5432/hrApplication
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=hrApplication
spring.datasource.password=hrApplication

# JPA Configuration for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

# Data Initialization
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:import-postgres.sql

# PostgreSQL specific settings
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true